In [2]:
print("Hello I'm excited to learn Pytorch")

Hello I'm excited to learn Pytorch


In [3]:
!nvidia-smi

Sat Dec 27 12:13:02 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.97                 Driver Version: 555.97         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   55C    P8             12W /   80W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
# Import the PyTorch library, used for deep learning and GPU acceleration
import torch  

# Import the pandas library, used for data manipulation and analysis (especially tabular data)
import pandas as pd  

# Import the NumPy library, used for numerical computations and handling arrays
import numpy as np  

# Import the matplotlib library's pyplot module, used for creating visualizations and plots
import matplotlib.pyplot as plt  

# Print the version of PyTorch currently installed, useful for verifying CUDA/GPU compatibility
print(torch.__version__)  


2.5.1+cu121


## Introduction to Tensors

Creating tensors

In [5]:
# Create a scalar (single number) tensor in PyTorch
scalar = torch.tensor(7)

# Display the tensor value; this will print "tensor(7)"
scalar


tensor(7)

In [6]:
# Check the number of dimensions of the tensor
scalar.ndim

0

In [7]:
# Extract the Python number from the tensor
# .item() converts a single-value tensor into a standard Python data type (int or float)
scalar.item()

7

In [8]:
# Create a 1-D tensor (vector) with two elements: [7, 7]
# Unlike a scalar (single number, 0-D), this is a sequence of values in one dimension
vector = torch.tensor([7, 7])

# Display the tensor; PyTorch will show it as tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim 

1

In [10]:
vector.shape 

torch.Size([2])

In [11]:


# Create a 2-D tensor (matrix) with two rows and two columns
# Each inner list represents a row of the matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

# Display the matrix; PyTorch will show it as:
# tensor([[ 7,  8],
#         [ 9, 10]])
MATRIX

# Check the number of dimensions of the tensor
print(MATRIX.ndim)   # Output: 2, meaning it's a matrix (2-D tensor)

# Check the shape of the tensor
print(MATRIX.shape)  # Output: torch.Size([2, 2]), meaning 2 rows and 2 columns


2
torch.Size([2, 2])


In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
# TENSOR 
# This is just a heading or label to indicate that the following code defines a tensor.

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
# torch.tensor(...) creates a tensor object in PyTorch.
# The input is a nested Python list, which PyTorch converts into a multi-dimensional tensor.
# [[[1,2,3], [3,6,9], [2,4,5]]] is a 3D list:
#   - The outermost brackets [ ... ] define one "batch" or one 3D block.
#   - Inside, there are 3 rows: [1,2,3], [3,6,9], [2,4,5].
#   - Each row contains 3 elements (columns).
# So the resulting tensor has shape (1, 3, 3):
#   - 1 block (depth dimension)
#   - 3 rows
#   - 3 columns

TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim # 3D tensor with shape (1 × 3 × 3)

3

In [15]:
TENSOR.shape 

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors 

In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8267, 0.3768, 0.0853, 0.0733],
        [0.0106, 0.6250, 0.3332, 0.7102],
        [0.6434, 0.6376, 0.9280, 0.0304]])

In [18]:
# Create a random tensor with similar shape to an image tensor 
# This comment describes the purpose: we want a tensor that mimics the structure of an image.

random_image_size_tensor = torch.rand(size=(224,224,3)) 
# torch.rand(...) generates a tensor filled with random numbers between 0 and 1.
# The argument size=(224,224,3) specifies the shape of the tensor:
#   - 224 → height (number of rows, like image pixels vertically)
#   - 224 → width (number of columns, like image pixels horizontally)
#   - 3   → color channels (Red, Green, Blue)
# So this creates a tensor that simulates a 224x224 RGB image.

random_image_size_tensor
# This line outputs the tensor when run in an interactive environment (like Jupyter Notebook).
# It will display the random values and confirm the shape torch.Size([224, 224, 3]).


tensor([[[0.6986, 0.0045, 0.6218],
         [0.5762, 0.4262, 0.4573],
         [0.4667, 0.2151, 0.0455],
         ...,
         [0.5334, 0.6555, 0.6546],
         [0.1281, 0.4498, 0.4712],
         [0.9555, 0.0745, 0.8353]],

        [[0.2797, 0.8796, 0.3814],
         [0.7415, 0.1128, 0.6990],
         [0.1877, 0.9608, 0.6060],
         ...,
         [0.4510, 0.9929, 0.1137],
         [0.4473, 0.8944, 0.9317],
         [0.0289, 0.5914, 0.0425]],

        [[0.0490, 0.5462, 0.5078],
         [0.4379, 0.3276, 0.1265],
         [0.0721, 0.4826, 0.8070],
         ...,
         [0.3300, 0.8347, 0.0572],
         [0.9878, 0.1724, 0.4461],
         [0.3272, 0.1175, 0.6402]],

        ...,

        [[0.6175, 0.9018, 0.2586],
         [0.0654, 0.2147, 0.9826],
         [0.2226, 0.7076, 0.2573],
         ...,
         [0.9659, 0.8510, 0.6498],
         [0.7404, 0.7807, 0.9765],
         [0.7917, 0.1118, 0.3152]],

        [[0.8145, 0.0871, 0.4489],
         [0.7848, 0.5601, 0.2127],
         [0.

In [19]:
random_image_size_tensor.shape 

torch.Size([224, 224, 3])

In [20]:
random_image_size_tensor.ndim 

3

## Zeros and Ones 

In [21]:
# Create a tensor of all zeros 
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype 

torch.float32

## Creating a range of tensors and tensors-like 

In [26]:
# Use torch.range() and get deprecated message, use torch.arange()
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
torch.__version__

'2.5.1+cu121'

In [28]:
# Creating tensors like 
ten_zeros = torch.zeros_like(input=one_to_ten)

In [29]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [30]:
# Float 32 Tensor
# This is a heading to indicate that the following code creates a tensor of floating-point numbers.

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)

# torch.tensor(...) creates a tensor object in PyTorch.
# [3.0, 6.0, 9.0] is the data: a Python list of floats.
# dtype=None → PyTorch automatically infers the data type. Since the values are floats, it defaults to torch.float32.
# device=None → The tensor will be created on the default device (usually the CPU).
# requires_grad=False → This tells PyTorch not to track gradients for this tensor (useful in training when you want to compute derivatives).
# So this line creates a 1D tensor with 3 elements: [3.0, 6.0, 9.0], stored as float32.

float_32_tensor
# This line outputs the tensor when run in an interactive environment (like Jupyter Notebook).
# It will display the values and confirm the type: torch.float32.


tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor 


tensor([3, 6, 9])

In [35]:
print(int_32_tensor.device)
print(float_32_tensor.device)


cpu
cpu


In [36]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors

In [37]:
some_tensor = torch.rand(3, 4)
some_tensor 

tensor([[0.1372, 0.2037, 0.1414, 0.1385],
        [0.1694, 0.6679, 0.3980, 0.8432],
        [0.8158, 0.9834, 0.9074, 0.7381]])

In [38]:
# Find out details about some tensor 
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.1372, 0.2037, 0.1414, 0.1385],
        [0.1694, 0.6679, 0.3980, 0.8432],
        [0.8158, 0.9834, 0.9074, 0.7381]])
Datatype of tensor: torch.float32
Shape of tensor: <built-in method size of Tensor object at 0x0000021491A4EB70>
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

In [39]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# Multipy tensor by 10  
tensor = tensor * 10 
tensor 

tensor([10, 20, 30])

In [41]:
# Substract 10 
tensor - 10 

tensor([ 0, 10, 20])

In [42]:
# Try out PyTorch in-built functions 
torch.mul(tensor,10)

tensor([100, 200, 300])

In [43]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix multiplications

In [44]:
# Element wise multiplication 
tensor * tensor 

tensor([100, 400, 900])

In [45]:
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [46]:
# Matrix multiplication 
torch.matmul(tensor, tensor)

tensor(1400)

In [47]:
print(torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape)  # multiply two random 10x10 matrices and show result shape (10,10)


torch.Size([10, 10])


### One of the most common errors in deep learning: shape errors

In [48]:
# Shape for matrix multiplications (we'll define two matrices and multiply them)

# Define a 3x2 tensor (matrix) with explicit integer values
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

# Define another 3x2 tensor (matrix) with explicit integer values
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm is an alias for torch.matmul when used with 2D matrices
# Perform matrix multiplication between tensor_A (3x2) and tensor_B (3x2)
# ⚠️ This will actually raise an error because the inner dimensions do not align:
# tensor_A is (3x2) and tensor_B is (3x2), so multiplication is not valid.
torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# To fix our Tensor shape issues, we can manipulate the shape of one of them using a transpose.
# A transpose switches the axes (rows become columns, columns become rows).
# tensor_B.T changes tensor_B from shape (3, 2) to shape (2, 3).
tensor_B.T 

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed,
# because transposing switches its shape from (3, 2) to (2, 3).
# This makes the inner dimensions align: tensor_A (3x2) × tensor_B.T (2x3) → result (3x3).

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")

# tensor_A keeps the same shape (3, 2), tensor_B.T changes to (2, 3)
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")

# Show the multiplication operation with aligned inner dimensions
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}  <- inner dimensions must match")

print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)

# Display the shape of the resulting matrix
print(f"\nOutput shape: {output.shape}")

# Final multiplication result (same as stored in 'output')
torch.matmul(tensor_A, tensor_B.T)


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])  <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor 
x = torch.arange(0,100, 10)
x, x.dtype


(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min 
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max 
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: torch.mean() requires the tensor to be of type float32 (not int)
# First approach: explicitly cast x to float32, then call torch.mean()
torch.mean(x.type(torch.float32))

# Second approach: cast x to float32, then use the built-in .mean() method of the tensor
x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [ ]:
# Find the sum 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max 

In [ ]:
# Find the position in the tensor that has the minimum value using argmin().
# argmin() returns the index position (as a single integer) of the first occurrence 
# of the minimum value in the flattened version of the tensor.
x.argmin()


tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()


tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, Stacking, Squeezing, and Unsqueezing Tensors

- **reshape** — Reshapes an input tensor to a defined shape.
- **view** — Returns a view of an input tensor with a specified shape while sharing the same underlying memory.
- **stack** — Combines multiple tensors either vertically (`vstack`) or horizontally (`hstack`).
- **squeeze** — Removes all dimensions of size `1` from a tensor.
- **unsqueeze** — Adds a dimension of size `1` at a specified position in a tensor.
- **permute** — Returns a view of the input tensor with its dimensions rearranged (swapped) in a specified order.


In [ ]:
# Let's create a tensor
import torch

x = torch.arange(1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension 
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5 
z, x 

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensor on top of each other 
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single-dimension entries from the tensor

print(f"Previous tensor : {x_reshaped}")        # Display the original reshaped tensor
print(f"Previous tensor : {x_reshaped}")        # Same print (duplicate) showing the tensor before squeezing

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()               # Apply squeeze() to drop all dimensions of size 1

print(f"\nNew tensor: {x_squeezed}")            # Display the squeezed tensor
print(f"\nNew shape: {x_squeezed.shape}")       # Show the new shape after squeezing


Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape 

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a tensor at a specific dimension index

print(f"Previous target: {x_squeezed}")          # Show the tensor before adding a new dimension
print(f"Previous shape: {x_squeezed.shape}")     # Display the shape before unsqueezing

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)       # Insert a new dimension at index 0

print(f"\nNew tensor: {x_unsqueezed}")           # Show the tensor after unsqueezing
print(f"\nNew shape: {x_unsqueezed.shape}")      # Display the updated shape with the new dimension


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a tensor in a specified order

x_original = torch.rand(size=(224, 224, 3))      # Create a tensor shaped [height, width, color_channels]

# Permute the original tensor to rearrange the axis (dimension) order
x_permuted = x_original.permute(2, 0, 1)         # Move dim 2 → 0, dim 0 → 1, dim 1 → 2 (HWC → CHW)

print(f"Previous shape: {x_original.shape}")                     # Show the original tensor shape
print(f"\nNew_shape: {x_permuted.shape}")          # Display the new shape after permuting


Previous shape: torch.Size([224, 224, 3])

New_shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.


In [ ]:
# Create a tensor
import torch                                   # Import the PyTorch library

x = torch.arange(1, 10).reshape(1, 3, 3)       # Create values 1–9 and reshape into a (1, 3, 3) tensor

x, x.shape                                     # Display the tensor and its shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our new tensors 
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [ ]:
# You can also use ":" to select "all" or a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

## Pytorch tensors & Numpy 


In [ ]:
import torch                 # Import PyTorch, which provides the tensor object and GPU acceleration
import numpy as np           # Import NumPy for numerical array operations

array = np.arange(1.0, 8.0)  # Create a NumPy array with values [1.0, 2.0, ..., 7.0]
tensor = torch.from_numpy(array)      # Convert the NumPy array to a PyTorch tensor (shares memory!)

array, tensor                # Display both objects to verify their values and dtypes


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Change the value of the array , what will this do to `tensor`
array = array + 1 
array, tensor 

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to Numpy array  
tensor = torch.ones(7)            # Create a PyTorch tensor filled with seven 1.0 values
numpy_tensor = tensor.numpy()     # Convert the tensor to a NumPy array (shares memory with tensor)
tensor, numpy_tensor              # Display both to verify values and dtypes


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype 

dtype('float32')

In [ ]:
# Change the tensor, what happen to `numpy_tensor`
tensor = tensor + 1 
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (removing randomness for consistent results)


In [ ]:
torch.rand(3,3)

tensor([[0.8747, 0.5936, 0.5069],
        [0.2069, 0.6962, 0.1580],
        [0.8126, 0.4841, 0.8025]])

In [ ]:
import torch                                   # Import PyTorch for tensor creation and operations

# create two random tensors 
random_tensor_A = torch.rand(3, 4)             # Create a 3×4 tensor with random values between 0 and 1
random_tensor_B = torch.rand(3, 4)             # Create another independent 3×4 random tensor

print(random_tensor_A, random_tensor_B)        # Print both tensors to inspect their values

print(random_tensor_A == random_tensor_B)      # Compare element‑wise to check where values are equal


tensor([[0.4079, 0.2043, 0.0960, 0.1714],
        [0.4266, 0.2309, 0.4517, 0.0118],
        [0.0041, 0.8283, 0.8001, 0.2523]]) tensor([[0.2977, 0.9693, 0.6346, 0.4624],
        [0.6567, 0.0114, 0.7375, 0.6478],
        [0.8773, 0.2032, 0.3789, 0.0513]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors 
import torch                                   # Import PyTorch for tensor operations

# Set the random seed  
RANDOM_SEED = 42                                # Define a fixed seed value for reproducibility
torch.manual_seed(RANDOM_SEED)                  # Apply the seed so random numbers become repeatable

random_tensor_C = torch.rand(3, 4)              # Create a 3×4 tensor with reproducible random values
random_tensor_D = torch.rand(3, 4)              # Create another 3×4 tensor with the next reproducible values

print(random_tensor_C)                          # Print the first random tensor
print(random_tensor_D)                          # Print the second random tensor
print(random_tensor_C == random_tensor_D)       # Compare tensors element‑wise for equality


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors 
import torch                                   # Import PyTorch for tensor operations

# Set the random seed  
RANDOM_SEED = 42                                # Define a fixed seed value for reproducibility
torch.manual_seed(RANDOM_SEED)                  # Apply the seed so random numbers become repeatable

random_tensor_C = torch.rand(3, 4)              # Generate a 3×4 tensor with reproducible random values

torch.manual_seed(RANDOM_SEED)                  # Reset the seed so the next tensor is identical to the first
random_tensor_D = torch.rand(3, 4)              # Generate another 3×4 tensor with the same reproducible values

print(random_tensor_C)                          # Print the first random tensor
print(random_tensor_D)                          # Print the second random tensor (identical to the first)
print(random_tensor_C == random_tensor_D)       # Compare tensors element‑wise for equality (all True)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (for faster computation)


In [ ]:
# conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
!nvidia-smi


Sun Dec 21 13:51:49 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.97                 Driver Version: 555.97         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8             10W /   93W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## 2. Check for GPU access with PyTorch


In [ ]:
# Check for GPU access with PyTorch 
import torch                          # Import PyTorch to work with tensors and GPU utilities
torch.cuda.is_available()             # Return True if a CUDA‑capable GPU is available to PyTorch


True

In [56]:
# Determine whether to use GPU ("cuda") or CPU based on system availability
device = "cuda" if torch.cuda.is_available() else "cpu"

# Show which device was selected
device


'cuda'

In [49]:
# Count number of devices 
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

In [54]:
# Create a tensor with values [1, 2, 3] and place it on the CPU instead of the GPU
tensor = torch.tensor([1, 2, 3])

# Print the tensor and display which device (CPU or GPU) it is stored on
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [57]:
# Move the existing tensor to the GPU (or stay on CPU if no GPU is available)
tensor_on_gpu = tensor.to(device)

# Display the tensor now located on the selected device
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to CPU 

In [ ]:
# If tensor is on GPU, can't transferm it back to NUMPY
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [60]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [61]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')